name: Terraform Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      action:
        description: "What do you want to do?"
        required: true
        type: choice
        options:
          - use_existing_file
          - create_new

      target_secret:
        description: "Which secret?"
        required: true
        type: choice
        options:
          - pipelines
          - microsoft
          - jumbo

      secret_value:
        description: "Paste value (only for create_new)"
        required: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="action=${{ github.event.inputs.action }}" \
            -var="target_secret=${{ github.event.inputs.target_secret }}" \
            -var="secret_value=${{ github.event.inputs.secret_value }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="action=${{ github.event.inputs.action }}" \
            -var="target_secret=${{ github.event.inputs.target_secret }}" \
            -var="secret_value=${{ github.event.inputs.secret_value }}"
